version: '2'

services:
  app:
    image: ruby:2.3.1
    working_dir: /app
    volumes:
      - '.:/app'
      - ruby-gems:/usr/local/bundle
    depends_on:
      - pg
      - mysql

  pg:
    image: postgres:9.4

  mysql:
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    image: mysql

volumes:
  ruby-gems:
    external:
      name: gems-ruby2

